export const LANGUAGES = { en: 'EN', ru: 'РУ', be: 'БЕ' };

export const TEMPERATURE_UNITS = { us: '°F', si: '°C' };

export const CONSTANTS = {
  en: {
    weekDay: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    weekDayShort: [
      'Sun',
      'Mon',
      'Tue',
      'Wed',
      'Thu',
      'Fri',
      'Sat',
    ],
    months: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    windUnits: 'm/s',
    apparentTempLabel: 'Feels like:',
    wind: 'Wind:',
    humidity: 'Humidity:',
    latitudeLabel: 'Latitude:',
    longitudeLabel: 'Longitude:',
    searchInputPlaceholder: 'Search for city',
    searchButtonText: 'SEARCH',
    speachLang: 'en_US',
  },
  ru: {
    weekDay: [
      'Воскресенье',
      'Понедельник',
      'Вторник',
      'Среда',
      'Четверг',
      'Пятница',
      'Суббота',
    ],
    weekDayShort: [
      'Вск',
      'Пнд',
      'Втр',
      'Срд',
      'Чтв',
      'Птн',
      'Сбт',
    ],
    months: [
      'Января',
      'Февраля',
      'Марта',
      'Апреля',
      'Мая',
      'Июня',
      'Июля',
      'Августа',
      'Сентября',
      'Октября',
      'Ноября',
      'Декабря',
    ],
    windUnits: 'м/с',
    apparentTempLabel: 'Ощущается как:',
    wind: 'Ветер:',
    humidity: 'Влажность:',
    latitudeLabel: 'Широта:',
    longitudeLabel: 'Долгота:',
    searchInputPlaceholder: 'Искать город',
    searchButtonText: 'ИСКАТЬ',
    speachLang: 'ru_RU',
  },
  be: {
    weekDay: [
      'Нядзеля',
      'Панядзелак',
      'Аўторак',
      'Серада',
      'Чацвер',
      'Пятніца',
      'Субота',
    ],
    weekDayShort: [
      'Няд',
      'Пнд',
      'Аўт',
      'Сер',
      'Чцв',
      'Пят',
      'Суб',
    ],
    months: [
      'Студзень',
      'Люты',
      'Сакавiк',
      'Красавiк',
      'Май',
      'Червень',
      'Лiпень',
      'Жнiвень',
      'Верасень',
      'Кастрычнiк',
      'Лiстапад',
      'Снежань',
    ],
    windUnits: 'м/с',
    apparentTempLabel: 'Адчуваецца як:',
    wind: 'Вецер:',
    humidity: 'Вільготнасць:',
    latitudeLabel: 'Шырата:',
    longitudeLabel: 'Даўгата:',
    searchInputPlaceholder: 'Шукаць горад',
    searchButtonText: 'ШУКАЦЬ',
    speachLang: 'be_BY',
  },
};

export const WEATHER_ICON_CLASSES = {
  'clear-day': 'icon-wi-day-sunny',
  'clear-night': 'icon-wi-night-clear',
  rain: 'icon-wi-rain',
  snow: 'icon-wi-snow',
  sleet: 'icon-wi-sleet',
  wind: 'icon-wi-windy',
  fog: 'icon-wi-fog',
  cloudy: 'icon-wi-cloudy',
  'partly-cloudy-day': 'icon-wi-day-cloudy',
  'partly-cloudy-night': 'icon-wi-night-cloudy',
};
